---
title: "Kendrick"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(httr)
library(tidytext)
library(topicmodels)
library(LDAvis)
library(lubridate)
library(rvest)
library(scales)
library(ggthemes)
library(wordcloud)
library(reshape2)
library(tm)
```


```{r get_artists}

get_artists <- function(artist_name) {
    
    # Search Spotify API for artist name
    res <- GET('https://api.spotify.com/v1/search', query = list(q = artist_name, type = 'artist')) %>%
        content %>% .$artists %>% .$items
    
    # Clean response and combine all returned artists into a dataframe
    artists <- map_df(seq_len(length(res)), function(x) {
        list(
            artist_name = res[[x]]$name,
            artist_uri = str_replace(res[[x]]$uri, 'spotify:artist:', ''), # remove meta info from the uri string
            artist_img = ifelse(length(res[[x]]$images) > 0, res[[x]]$images[[1]]$url, NA)
        )
    })
    
    return(artists)
}

artist_info <- get_artists('kendrick+lamar')

# Filter out other artist matches
artist_info <- artist_info %>% 
    filter(artist_name == 'Kendrick Lamar')

str(artist_info)
```

```{r get_albums}
get_albums <- function(artist_uri) {
    albums <- GET(paste0('https://api.spotify.com/v1/artists/', artist_uri,'/albums')) %>% content
    
    map_df(1:length(albums$items), function(x) {
        tmp <- albums$items[[x]]
        
        # Make sure the album_type is not "single"
        if (tmp$album_type == 'album') {
            data.frame(album_uri = str_replace(tmp$uri, 'spotify:album:', ''),
                       album_name = str_replace_all(tmp$name, '\'', ''),
                       album_img = albums$items[[x]]$images[[1]]$url,
                       stringsAsFactors = F) %>%
                mutate(album_release_date = GET(paste0('https://api.spotify.com/v1/albums/', str_replace(tmp$uri, 'spotify:album:', ''))) %>% content %>% .$release_date, # you need a separate call to on "albums" to get release date.
                       album_release_year = ifelse(nchar(album_release_date) == 4, year(as.Date(album_release_date, '%Y')), year(as.Date(album_release_date, '%Y-%m-%d'))) # not all album_release_dates have months, so I created album_release year for sorting
                       )
        } else {
            NULL
        }
        
    }) %>% filter(!duplicated(tolower(album_name))) %>%  # Sometimes there are multiple versions (just with different capitalizations) of the same album
        arrange(album_release_year)
}

album_info <- get_albums(artist_info$artist_uri)

# Filter out deluxe edition of good kid, m.A.A.d. city and Welcome to Compton
non_studio_albums <- c('good kid, m.A.A.d city (Deluxe)', 'Welcome to Compton')
album_info <- filter(album_info, !album_name %in% non_studio_albums)

album_info
```

```{r get_tracks}
## Get tracks
get_tracks <- function(artist_info, album_info) {
    
    client_id <- 'fa98555660084d0b82471bcccedd65c8'
    client_secret <- '7319c725f5c0469082b7ac663f02065e'
    access_token <- POST('https://accounts.spotify.com/api/token',
                         accept_json(), authenticate(client_id, client_secret),
                         body = list(grant_type='client_credentials'),
                         encode = 'form', httr::config(http_version=2)) %>% content %>% .$access_token
    
    track_info <- map_df(album_info$album_uri, function(x) {
        tracks <- GET(paste0('https://api.spotify.com/v1/albums/', x, '/tracks')) %>% 
            content %>% 
            .$items 
        
        uris <- map(1:length(tracks), function(z) {
            gsub('spotify:track:', '', tracks[z][[1]]$uri)
        }) %>% unlist %>% paste0(collapse=',')
        
        res <- GET(paste0('https://api.spotify.com/v1/audio-features/?ids=', uris),
                   query = list(access_token = access_token)) %>% content %>% .$audio_features
        df <- unlist(res) %>% 
            matrix(nrow = length(res), byrow = T) %>% 
            as.data.frame(stringsAsFactors = F)
        names(df) <- names(res[[1]])
        df <- df %>% 
            mutate(album_uri = x,
                   track_number = row_number()) %>% 
            rowwise %>% 
            mutate(track_name = tracks[[track_number]]$name) %>%
            ungroup %>% 
            left_join(album_info, by = 'album_uri') %>% 
            rename(track_uri = id) %>% 
            select(-c(type, track_href, analysis_url, uri))
        return(df)
    }) %>%
        mutate(artist_img = artist_info$artist_img) %>% 
        mutate_at(c('album_uri', 'track_uri', 'album_release_date', 'track_name', 'album_name', 'artist_img'), funs(as.character)) %>%
        mutate_at(c('danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'album_release_year',
                    'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'time_signature', 'track_number'), funs(as.numeric(gsub('[^0-9.-]+', '', as.character(.))))) # for some reason parse_number() from readr doesn't work here
    return(track_info)
}

spotify_df <- get_tracks(artist_info, album_info)

# Get rid of the remixes of Bitch, Don't Kill My Vibe
spotify_df <- spotify_df %>% filter(track_name != "Bitch, Don’t Kill My Vibe - Remix", track_name != "Bitch, Don’t Kill My Vibe - International Remix / Explicit Version")
```

```{r genius_get_artists}
##### Genius Lyrics
token <- '0lokoRjkqEptGnYolES38msiGzQrkzaN3lVuw9yRnJ709vbCqtubHkD_8OB5f6Jc'

genius_get_artists <- function(artist_name, n_results = 10) {
    baseURL <- 'https://api.genius.com/search?q=' 
    requestURL <- paste0(baseURL, gsub(' ', '%20', artist_name),
                         '&per_page=', n_results,
                         '&access_token=', token)
    
    res <- GET(requestURL) %>% content %>% .$response %>% .$hits
    
    map_df(1:length(res), function(x) {
        tmp <- res[[x]]$result$primary_artist
        list(
            artist_id = tmp$id,
            artist_name = tmp$name
        )
    }) %>% unique
}

genius_artists <- genius_get_artists('Kendrick Lamar')
genius_artists
```

```{r genius_get_track_urls}
## Get track urls
baseURL <- 'https://api.genius.com/artists/' 
requestURL <- paste0(baseURL, genius_artists$artist_id[1], '/songs')

track_lyric_urls <- list()
i <- 1
while (i > 0) {
    tmp <- GET(requestURL, query = list(access_token = token, per_page = 50, page = i)) %>% content %>% .$response
    track_lyric_urls <- c(track_lyric_urls, tmp$songs)
    if (!is.null(tmp$next_page)) {
        i <- tmp$next_page
    } else {
        break
    }
}

length(track_lyric_urls)
summary(track_lyric_urls[[1]])

filtered_track_lyric_urls <- c()
filtered_track_lyric_titles <- c()
filtered_track_annotations <- c()
filtered_track_pageviews <- c()
index <- c()

# Keep only the songs where Kendrick is the primary artist.
for (i in 1:length(track_lyric_urls)) {
        if (track_lyric_urls[[i]]$primary_artist$name == "Kendrick Lamar") {
                filtered_track_lyric_urls <- append(filtered_track_lyric_urls, track_lyric_urls[[i]]$url)
                filtered_track_lyric_titles <- append(filtered_track_lyric_titles, track_lyric_urls[[i]]$title)
                filtered_track_annotations <- append(filtered_track_annotations, track_lyric_urls[[i]]$annotation_count)
                if (!is.null(track_lyric_urls[[i]]$stats$pageviews)) {
                        filtered_track_pageviews <- append(filtered_track_pageviews, track_lyric_urls[[i]]$stats$pageviews)
                } else {
                        filtered_track_pageviews <- append(filtered_track_pageviews, NA)
                }
                index <- append(index, i)
        }
}

# Fix the mismatches between Spotify's naming and Genius's naming.
filtered_track_lyric_titles[filtered_track_lyric_titles == 'Ignorance is Bliss'] <- "Ignorance Is Bliss"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'Alien Girl (Today With Her)'] <- "Alien Girl (Today W/ Her)"
filtered_track_lyric_titles[filtered_track_lyric_titles == "H.O.C."] <- "H.O.C"
filtered_track_lyric_titles[filtered_track_lyric_titles == "Fuck Your Ethnicity"] <- "F*ck Your Ethnicity"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'No Makeup (Her Vice)'] <- "No Make-Up (Her Vice)"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'Ronald Reagan Era (His Evils)'] <- "Ronald Reagan Era"
filtered_track_lyric_titles[filtered_track_lyric_titles == "Poe Man's Dream (His Vice)"] <- "Poe Mans Dreams (His Vice)"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'Kush & Corinthians (His Pain)'] <- "Kush & Corinthians"
filtered_track_lyric_titles[filtered_track_lyric_titles == "Ab-Soul's Outro"] <- "Ab-Souls Outro"
filtered_track_lyric_titles[filtered_track_lyric_titles == "Sherane a.k.a Master Splinter's Daughter"] <- "Sherane a.k.a Master Splinter’s Daughter"
filtered_track_lyric_titles[filtered_track_lyric_titles == "Bitch, Don't Kill My Vibe"] <- "Bitch, Don’t Kill My Vibe"
filtered_track_lyric_titles[119] <- "good kid"
filtered_track_lyric_titles[198] <- "m.A.A.d city"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'Swimming Pools (Drank)'] <- "Swimming Pools (Drank) - Extended Version"
filtered_track_lyric_titles[filtered_track_lyric_titles == "Sing About Me, I'm Dying of Thirst"] <- "Sing About Me, I'm Dying Of Thirst"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'For Free? (Interlude)'] <- "For Free? - Interlude"
filtered_track_lyric_titles[320] <- "u"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'For Sale? (Interlude)'] <- "For Sale? - Interlude"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'How Much a Dollar Cost'] <- "How Much A Dollar Cost"
filtered_track_lyric_titles[filtered_track_lyric_titles == 'The Blacker the Berry'] <- "The Blacker The Berry"
filtered_track_lyric_titles[153] <- "i"
filtered_track_lyric_titles[322] <- "untitled 01 | 08.19.2014."
filtered_track_lyric_titles[323] <- "untitled 02 | 06.23.2014."
filtered_track_lyric_titles[324] <- "untitled 03 | 05.28.2013."
filtered_track_lyric_titles[325] <- "untitled 04 | 08.14.2014."
filtered_track_lyric_titles[326] <- "untitled 05 | 09.21.2014."
filtered_track_lyric_titles[327] <- "untitled 06 | 06.30.2014."
filtered_track_lyric_titles[328] <- "untitled 07 | 2014 - 2016"
filtered_track_lyric_titles[330] <- "untitled 08 | 09.06.2014."
filtered_track_lyric_titles[filtered_track_lyric_titles == "LOYALTY."] <- "LOYALTY. FEAT. RIHANNA."
filtered_track_lyric_titles[filtered_track_lyric_titles == "LOVE."] <- "LOVE. FEAT. ZACARI."
filtered_track_lyric_titles[filtered_track_lyric_titles == "XXX."] <- "XXX. FEAT. U2."


# Check to make sure all of the album songs are now present in the filtered track lyric titles.
spotify_df$track_name[!spotify_df$track_name %in% filtered_track_lyric_titles]

length(spotify_df$track_name[spotify_df$track_name %in% filtered_track_lyric_titles]) == length(spotify_df$track_name)

# Keep only the urls for the songs in the full-length albums.
track_urls <- filtered_track_lyric_urls[filtered_track_lyric_titles %in% spotify_df$track_name]
track_titles <- filtered_track_lyric_titles[filtered_track_lyric_titles %in% spotify_df$track_name]
track_annotations <- filtered_track_annotations[filtered_track_lyric_titles %in% spotify_df$track_name]
track_pageviews <- filtered_track_pageviews[filtered_track_lyric_titles %in% spotify_df$track_name]

# Make sure they're the same length.
length(track_urls)
length(track_titles)
length(track_annotations)
length(track_pageviews)

```

```{r scrape_lyrics}
lyric_scraper <- function(url) {
    read_html(url) %>% 
        html_node('lyrics') %>% 
        html_text
}

genius_df <- map_df(1:length(track_urls), function(x) {
    # add in error handling
    lyrics <- try(lyric_scraper(track_urls[x]))
    if (class(lyrics) != 'try-error') {
        # strip out non-lyric text and extra spaces
        #lyrics <- str_replace_all(lyrics, '\\[(Verse [[:digit:]]|Pre-Chorus [[:digit:]]|Hook [[:digit:]]|Produced by [[\w+]]|Chorus|Outro|Verse|Refrain|Hook|Bridge|Intro|Instrumental|Pre-Chorus)\\]|[[:digit:]]|[\\.!?\\(\\)\\[\\],]', '')
        lyrics <- str_replace_all(lyrics, '\\n', ' ')
        lyrics <- str_replace_all(lyrics, '\\[(.*?)\\]', '')
        lyrics <- str_replace_all(lyrics, '([A-Z])', ' \\1')
        lyrics <- str_replace_all(lyrics, ' {2,}', ' ')
        lyrics <- tolower(str_trim(lyrics))
    } else {
        lyrics <- NA
    }
    
    tots <- list(
        track_name = track_titles[x],
        lyrics = lyrics,
        annotations = track_annotations[x],
        pageviews = track_pageviews[x]
    )
    
    return(tots)
})

head(genius_df)
```

```{r join_all}
new_genius_df <- genius_df %>% 
    mutate(track_name_join = tolower(str_replace(track_name, '[[:punct:]]', ''))) %>% 
    filter(!duplicated(track_name_join)) %>% 
    select(-track_name)

track_df <- spotify_df %>%
    mutate(track_name_join = tolower(str_replace(track_name, '[[:punct:]]', ''))) %>%
    left_join(new_genius_df, by = 'track_name_join')

# Add a career-wide track number.
track_df$career_track_number <- 1:dim(track_df)[1]

# Add the character count for each set of lyrics.
track_df$song_char_count <- nchar(track_df$lyrics)

# Add the word count.
word_count <- c()
for (i in 1:length(track_df$lyrics)) {
        word_count <- append(word_count, length(strsplit(track_df$lyrics[i],' ')[[1]]))
}
track_df$song_word_count <- word_count

write.csv(track_df, "../data/kendrick_data.csv")
```

```{r viz, fig.width=11, fig.height=4}
# Load it up.
kendrick <- read.csv("../data/kendrick_data.csv")

# Fix the factor levels for the albums.
kendrick$album_name <- factor(kendrick$album_name, levels = c("Overly Dedicated", "Section.80", "good kid, m.A.A.d city", "To Pimp A Butterfly", "untitled unmastered.", "DAMN."))

# Remove Overly Dedicated (a non-studio album)
kendrick <- kendrick %>% filter(album_name != "Overly Dedicated")

# Get word counts for each album.
album_word_counts <- kendrick %>% group_by(album_name) %>% summarise(word_count = sum(song_word_count))

ggplot(kendrick) +
        geom_col(aes(x = track_number, y = annotations/song_word_count, fill = album_name), show.legend = FALSE) +
        facet_grid(~album_name, scales = "free_x", space = "free_x") +
        scale_x_continuous(breaks= c(2,4,6,8,10,12,14,16)) +
        theme_tufte(base_family = 'GillSans')

```

SENTIMENT ANALYSIS

```{r sentiment}
# Change the text from factor to character.
kendrick$lyrics <- as.character(kendrick$lyrics)

# Get one word per row.
tidy_kendrick <- kendrick %>% unnest_tokens(word, lyrics)

# Remove stop words.
cleaned_kendrick <- tidy_kendrick %>%
        anti_join(stop_words)

# Check out the most common words in the corpus.
cleaned_kendrick %>%
        count(word, sort = TRUE) %>% 
        head()

# Get the sentiment of the Bing lexicon.
bing <- get_sentiments("bing")

# Get the sentiment across the tracks.
kendrick_sentiment <- cleaned_kendrick %>%
        inner_join(bing) %>%
        count(track_name, sentiment) %>%
        spread(sentiment, n, fill = 0) %>%
        mutate(sentiment = (positive - negative)/(positive + negative))

kendrick <- inner_join(kendrick, kendrick_sentiment)

kendrick <- kendrick %>% mutate(smart_sentiment = (sentiment + (valence*2)-1)/2)

kendrick

cleaned_kendrick$track_name[cleaned_kendrick$word == "complicated"]
```

```{r sentiment_viz, fig.width=11, fig.height=4, warning=FALSE, message=FALSE}
# See how the sentiment changes across the post order.
ggplot(kendrick, aes(x = track_number, y = smart_sentiment, color = smart_sentiment)) +
        geom_hline(aes(yintercept=1, color=1), linetype="dashed", show.legend = FALSE) +
        geom_hline(aes(yintercept=0.5, color=0.5), linetype="dashed", show.legend = FALSE) +
        geom_hline(aes(yintercept=0, color=0), linetype="dashed", show.legend = FALSE) +
        geom_hline(aes(yintercept=-0.5, color=-0.5), linetype="dashed", show.legend = FALSE) +
        geom_hline(aes(yintercept=-1, color=-1), linetype="dashed", show.legend = FALSE) +
        #geom_line(aes(color=..y..)) +
        geom_smooth(aes(color=..y..), size = 2, show.legend = FALSE, se = FALSE, span = 0.3) +
        geom_smooth(color="black", size = 0.3, show.legend = FALSE, alpha = 0.9, se = FALSE, span = 0.3) +
        #geom_point(color = "black", size=2, show.legend = FALSE) +
        facet_grid(~album_name, scales = "free_x", space = "free_x") +
        scale_x_continuous(breaks= c(2,4,6,8,10,12,14,16)) +
        scale_color_distiller(type = "div", palette = "RdYlGn", direction = 1, values = c(0,0.5,1)) +
        theme_tufte(base_family = 'GillSans') +
        labs(title = "Sentiment in Kendrick Lamar's Music and Lyrics") +
        xlab("") +
        ylab("") +
        scale_y_continuous(limits = c(-1,1),
                           labels = c("very negative", 
                                      "negative", 
                                      "neutral", 
                                      "positive", 
                                      "very positive"))
```

```{r word_clouds}
# Get the words contribute most to each sentiment.
bing_word_counts <- tidy_kendrick %>%
        inner_join(bing) %>%
        count(word, sentiment, sort = TRUE) %>%
        ungroup()

# View them.
bing_word_counts %>%
        filter(n > 20) %>%
        mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_bar(stat = "identity", alpha = 0.8) +
        scale_fill_manual(values = c("red", "#3CDE00")) +
        theme(axis.text.x = element_text(angle = 0, hjust = 1)) +
        ylab("Contribution to sentiment") +
        coord_flip()

# See a word cloud of the top words by word count.
cleaned_kendrick %>%
        count(word) %>%
        with(wordcloud(word, n, max.words = 100))

# Colored by sentiment.
tidy_kendrick %>%
        inner_join(bing) %>%
        count(word, sentiment, sort = TRUE) %>%
        acast(word ~ sentiment, value.var = "n", fill = 0) %>%
        comparison.cloud(colors = c("red", "#3CDE00"),
                         max.words = 100)

tidy_kendrick
```

TOPIC MODELLING

```{r tfidf, fig.width=10, fig.height=4}
# Get the word counts for each track.
word_counts <- tidy_kendrick %>%
        select(album_name, track_number, track_name, word) %>% 
        anti_join(stop_words) %>%
        count(album_name, track_number, track_name, word, sort = TRUE) %>% 
        ungroup() %>% 
        left_join(album_word_counts)

# Take a look.
head(word_counts)

# Get the tf-idf
album_words <- word_counts %>%
  bind_tf_idf(word, album_name, n)

# Take a look.
head(album_words)

# Look at the words with the highest tf-idf.
album_words %>%
  select(-word_count) %>%
  arrange(desc(tf_idf))

# Look at the words with the highest tf-idf within DAMN.
album_words %>%
  filter(album_name == "To Pimp A Butterfly") %>%
  select(-word_count) %>%
  arrange(desc(tf_idf))

plot_albums <- album_words %>%
  arrange(desc(tf_idf)) %>%
  mutate(word = factor(word, levels = rev(unique(word))))

plot_albums %>% 
        group_by(album_name) %>%
        top_n(5) %>%
        ungroup %>%
        ggplot(aes(word, tf_idf, fill = album_name)) +
        geom_col(show.legend = FALSE) +
        labs(x = NULL, y = "tf-idf") +
        facet_wrap(~album_name, nrow = 1, scales = "free") +
        coord_flip()

```

```{r word_clouds, warning = FALSE}
# Word cloud for Section.80
layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "Section.80")
plot_albums[plot_albums$album_name == "Section.80",] %>%
        with(wordcloud(word, tf_idf, max.words = 75, random.order = F))

# Word cloud for good kid
layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "good kid, m.A.A.d city")
plot_albums[plot_albums$album_name == "good kid, m.A.A.d city",] %>%
        with(wordcloud(word, tf_idf, max.words = 75, random.order = F))

# Word cloud for TPAB
layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "To Pimp A Butterfly")
plot_albums[plot_albums$album_name == "To Pimp A Butterfly",] %>%
        with(wordcloud(word, tf_idf, max.words = 75, random.order = F))

# Word cloud for untitled unmastered.
layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "untitled unmastered.")
plot_albums[plot_albums$album_name == "untitled unmastered.",] %>%
        with(wordcloud(word, tf_idf, max.words = 75, random.order = F))

# Word cloud for DAMN.
layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "DAMN.")
plot_albums[plot_albums$album_name == "DAMN.",] %>%
        with(wordcloud(word, tf_idf, max.words = 75, random.order = F))
```


```{r topic}
album_words_filtered <- album_words[album_words$album_name == "DAMN.",] %>%
        top_n(2000, tf_idf) %>% 
        unite(album_track, album_name, track_number)

# Create the document-term matrix.
tracks_dtm <- album_words_filtered %>%
  cast_dtm(album_track, word, n)

# Fit a Latent Dirichlet Allocation model.
tracks_lda <- LDA(tracks_dtm, k = 6, control = list(seed = 1))
tracks_lda_td <- tidy(tracks_lda)

top_terms <- tracks_lda_td %>%
        group_by(topic) %>%
        top_n(4, beta) %>%
        ungroup() %>%
        arrange(topic, -beta)

top_terms %>%
        mutate(term = reorder(term, beta)) %>%
        ggplot(aes(term, beta)) +
        geom_bar(stat = "identity") +
        facet_wrap(~ topic, scales = "free") +
        coord_cartesian(xlim=c(0, 5)) +
        theme(axis.text.x = element_text(size = 1, angle = 0, hjust = 1)) +
        coord_flip()
```

```{r testing for relationships}
# Danceable songs are less likely to be annotated.
ggplot(kendrick) +
        geom_point(aes(x = danceability, y = (annotations/song_word_count))) +
        geom_smooth(aes(x = danceability, y = (annotations/song_word_count)), method = "lm")

summary(lm(I(annotations/song_word_count) ~ danceability, kendrick))

# Danceable songs are less likely to be annotated.
ggplot(kendrick) +
        geom_point(aes(x = energy, y = (annotations/song_word_count))) +
        geom_smooth(aes(x = energy, y = (annotations/song_word_count)), method = "lm")

summary(lm(I(annotations/song_word_count) ~ energy, kendrick))

```



Sources:

http://tidytextmining.com/tfidf.html#the-bind_tf_idf-function
https://cran.r-project.org/web/packages/tidytext/vignettes/tf_idf.html
https://cran.r-project.org/web/packages/tidytext/vignettes/topic_modeling.html






